package com.hitzd.his.casehistory.beans.operation;

import java.util.Date;

/**
 * Operation generated by MyEclipse Persistence Tools
 */

public class Operation implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -5913038613614021121L;

	private String patientId;

	private Long visitId;

	private Long operationNo;

	private String operationDesc;

	private String operationCode;

	private String heal;

	private String woundGrade;

	private Date operatingDate;

	private String anaesthesiaMethod;

	private String operator;

	private String firstAssistant;

	private String secondAssistant;

	private String anesthesiaDoctor;

	private Date linkDate;

	public String getAnaesthesiaMethod() {
		return anaesthesiaMethod;
	}

	public void setAnaesthesiaMethod(String anaesthesiaMethod) {
		this.anaesthesiaMethod = anaesthesiaMethod;
	}

	public String getAnesthesiaDoctor() {
		return anesthesiaDoctor;
	}

	public void setAnesthesiaDoctor(String anesthesiaDoctor) {
		this.anesthesiaDoctor = anesthesiaDoctor;
	}

	public String getFirstAssistant() {
		return firstAssistant;
	}

	public void setFirstAssistant(String firstAssistant) {
		this.firstAssistant = firstAssistant;
	}

	public String getHeal() {
		return heal;
	}

	public void setHeal(String heal) {
		this.heal = heal;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public Date getOperatingDate() {
		return operatingDate;
	}

	public void setOperatingDate(Date operatingDate) {
		this.operatingDate = operatingDate;
	}

	public String getOperationCode() {
		return operationCode;
	}

	public void setOperationCode(String operationCode) {
		this.operationCode = operationCode;
	}

	public String getOperationDesc() {
		return operationDesc;
	}

	public void setOperationDesc(String operationDesc) {
		this.operationDesc = operationDesc;
	}

	public Long getOperationNo() {
		return operationNo;
	}

	public void setOperationNo(Long operationNo) {
		this.operationNo = operationNo;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getSecondAssistant() {
		return secondAssistant;
	}

	public void setSecondAssistant(String secondAssistant) {
		this.secondAssistant = secondAssistant;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

	public String getWoundGrade() {
		return woundGrade;
	}

	public void setWoundGrade(String woundGrade) {
		this.woundGrade = woundGrade;
	}
	
	
}