package com.hitzd.his.casehistory.beans.operation;

import java.util.Date;

/**
 * OperationMaster generated by MyEclipse Persistence Tools
 */

public class OperationMaster implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -546201314909591959L;

	private String patientId;

	private Long visitId;

	private Long operId;

	private String deptStayed;

	private String operatingRoom;

	private String operatingRoomNo;

	private String diagBeforeOperation;

	private String patientCondition;

	private String operationScale;

	private String diagAfterOperation;

	private Long emergencyIndicator;

	private Long isolationIndicator;

	private String operationClass;

	private String operatingDept;

	private String surgeon;

	private String firstAssistant;

	private String secondAssistant;

	private String thirdAssistant;

	private String fourthAssistant;

	private String anesthesiaMethod;

	private String anesthesiaDoctor;

	private String anesthesiaAssistant;

	private String bloodTranDoctor;

	private String firstOperationNurse;

	private String secondOperationNurse;

	private String firstSupplyNurse;

	private String secondSupplyNurse;

	private Long nurseShiftIndicator;

	private Date startDateTime;

	private Date endDateTime;

	private Long satisfactionDegree;

	private Long smoothIndicator;

	private Long inFluidsAmount;

	private Long outFluidsAmount;

	private Long bloodLossed;

	private Long bloodTransfered;

	private String enteredBy;

	private String thirdSupplyNurse;

	private Long orderTransfer;

	private Long chargeTransfer;

	private Long endIndicator;

	private Long bloodWholeSelf;

	private Long bloodWhole;

	private Long bloodRbc;

	private Long bloodPlasm;

	private Long bloodOther;

	private Long sequence;

	private String preAnesResult;

	private Date receiveInDate;

	private Date sendOutDate;

	private Long bedNo;

	private Long operProg;

	private String operMemo;

	private String deptName;

	private Long clinicAttr;

	private Long outpOrInp;

	private Long internalOrSergery;

	private Date linkDate;

	public String getAnesthesiaAssistant() {
		return anesthesiaAssistant;
	}

	public void setAnesthesiaAssistant(String anesthesiaAssistant) {
		this.anesthesiaAssistant = anesthesiaAssistant;
	}

	public String getAnesthesiaDoctor() {
		return anesthesiaDoctor;
	}

	public void setAnesthesiaDoctor(String anesthesiaDoctor) {
		this.anesthesiaDoctor = anesthesiaDoctor;
	}

	public String getAnesthesiaMethod() {
		return anesthesiaMethod;
	}

	public void setAnesthesiaMethod(String anesthesiaMethod) {
		this.anesthesiaMethod = anesthesiaMethod;
	}

	public Long getBedNo() {
		return bedNo;
	}

	public void setBedNo(Long bedNo) {
		this.bedNo = bedNo;
	}

	public Long getBloodLossed() {
		return bloodLossed;
	}

	public void setBloodLossed(Long bloodLossed) {
		this.bloodLossed = bloodLossed;
	}

	public Long getBloodOther() {
		return bloodOther;
	}

	public void setBloodOther(Long bloodOther) {
		this.bloodOther = bloodOther;
	}

	public Long getBloodPlasm() {
		return bloodPlasm;
	}

	public void setBloodPlasm(Long bloodPlasm) {
		this.bloodPlasm = bloodPlasm;
	}

	public Long getBloodRbc() {
		return bloodRbc;
	}

	public void setBloodRbc(Long bloodRbc) {
		this.bloodRbc = bloodRbc;
	}

	public String getBloodTranDoctor() {
		return bloodTranDoctor;
	}

	public void setBloodTranDoctor(String bloodTranDoctor) {
		this.bloodTranDoctor = bloodTranDoctor;
	}

	public Long getBloodTransfered() {
		return bloodTransfered;
	}

	public void setBloodTransfered(Long bloodTransfered) {
		this.bloodTransfered = bloodTransfered;
	}

	public Long getBloodWhole() {
		return bloodWhole;
	}

	public void setBloodWhole(Long bloodWhole) {
		this.bloodWhole = bloodWhole;
	}

	public Long getBloodWholeSelf() {
		return bloodWholeSelf;
	}

	public void setBloodWholeSelf(Long bloodWholeSelf) {
		this.bloodWholeSelf = bloodWholeSelf;
	}

	public Long getChargeTransfer() {
		return chargeTransfer;
	}

	public void setChargeTransfer(Long chargeTransfer) {
		this.chargeTransfer = chargeTransfer;
	}

	public Long getClinicAttr() {
		return clinicAttr;
	}

	public void setClinicAttr(Long clinicAttr) {
		this.clinicAttr = clinicAttr;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptStayed() {
		return deptStayed;
	}

	public void setDeptStayed(String deptStayed) {
		this.deptStayed = deptStayed;
	}

	public String getDiagAfterOperation() {
		return diagAfterOperation;
	}

	public void setDiagAfterOperation(String diagAfterOperation) {
		this.diagAfterOperation = diagAfterOperation;
	}

	public String getDiagBeforeOperation() {
		return diagBeforeOperation;
	}

	public void setDiagBeforeOperation(String diagBeforeOperation) {
		this.diagBeforeOperation = diagBeforeOperation;
	}

	public Long getEmergencyIndicator() {
		return emergencyIndicator;
	}

	public void setEmergencyIndicator(Long emergencyIndicator) {
		this.emergencyIndicator = emergencyIndicator;
	}

	public Date getEndDateTime() {
		return endDateTime;
	}

	public void setEndDateTime(Date endDateTime) {
		this.endDateTime = endDateTime;
	}

	public Long getEndIndicator() {
		return endIndicator;
	}

	public void setEndIndicator(Long endIndicator) {
		this.endIndicator = endIndicator;
	}

	public String getEnteredBy() {
		return enteredBy;
	}

	public void setEnteredBy(String enteredBy) {
		this.enteredBy = enteredBy;
	}

	public String getFirstAssistant() {
		return firstAssistant;
	}

	public void setFirstAssistant(String firstAssistant) {
		this.firstAssistant = firstAssistant;
	}

	public String getFirstOperationNurse() {
		return firstOperationNurse;
	}

	public void setFirstOperationNurse(String firstOperationNurse) {
		this.firstOperationNurse = firstOperationNurse;
	}

	public String getFirstSupplyNurse() {
		return firstSupplyNurse;
	}

	public void setFirstSupplyNurse(String firstSupplyNurse) {
		this.firstSupplyNurse = firstSupplyNurse;
	}

	public String getFourthAssistant() {
		return fourthAssistant;
	}

	public void setFourthAssistant(String fourthAssistant) {
		this.fourthAssistant = fourthAssistant;
	}

	public Long getInFluidsAmount() {
		return inFluidsAmount;
	}

	public void setInFluidsAmount(Long inFluidsAmount) {
		this.inFluidsAmount = inFluidsAmount;
	}

	public Long getInternalOrSergery() {
		return internalOrSergery;
	}

	public void setInternalOrSergery(Long internalOrSergery) {
		this.internalOrSergery = internalOrSergery;
	}

	public Long getIsolationIndicator() {
		return isolationIndicator;
	}

	public void setIsolationIndicator(Long isolationIndicator) {
		this.isolationIndicator = isolationIndicator;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public Long getNurseShiftIndicator() {
		return nurseShiftIndicator;
	}

	public void setNurseShiftIndicator(Long nurseShiftIndicator) {
		this.nurseShiftIndicator = nurseShiftIndicator;
	}

	public String getOperatingDept() {
		return operatingDept;
	}

	public void setOperatingDept(String operatingDept) {
		this.operatingDept = operatingDept;
	}

	public String getOperatingRoom() {
		return operatingRoom;
	}

	public void setOperatingRoom(String operatingRoom) {
		this.operatingRoom = operatingRoom;
	}

	public String getOperatingRoomNo() {
		return operatingRoomNo;
	}

	public void setOperatingRoomNo(String operatingRoomNo) {
		this.operatingRoomNo = operatingRoomNo;
	}

	public String getOperationClass() {
		return operationClass;
	}

	public void setOperationClass(String operationClass) {
		this.operationClass = operationClass;
	}

	public String getOperationScale() {
		return operationScale;
	}

	public void setOperationScale(String operationScale) {
		this.operationScale = operationScale;
	}

	public Long getOperId() {
		return operId;
	}

	public void setOperId(Long operId) {
		this.operId = operId;
	}

	public String getOperMemo() {
		return operMemo;
	}

	public void setOperMemo(String operMemo) {
		this.operMemo = operMemo;
	}

	public Long getOperProg() {
		return operProg;
	}

	public void setOperProg(Long operProg) {
		this.operProg = operProg;
	}

	public Long getOrderTransfer() {
		return orderTransfer;
	}

	public void setOrderTransfer(Long orderTransfer) {
		this.orderTransfer = orderTransfer;
	}

	public Long getOutFluidsAmount() {
		return outFluidsAmount;
	}

	public void setOutFluidsAmount(Long outFluidsAmount) {
		this.outFluidsAmount = outFluidsAmount;
	}

	public Long getOutpOrInp() {
		return outpOrInp;
	}

	public void setOutpOrInp(Long outpOrInp) {
		this.outpOrInp = outpOrInp;
	}

	public String getPatientCondition() {
		return patientCondition;
	}

	public void setPatientCondition(String patientCondition) {
		this.patientCondition = patientCondition;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getPreAnesResult() {
		return preAnesResult;
	}

	public void setPreAnesResult(String preAnesResult) {
		this.preAnesResult = preAnesResult;
	}

	public Date getReceiveInDate() {
		return receiveInDate;
	}

	public void setReceiveInDate(Date receiveInDate) {
		this.receiveInDate = receiveInDate;
	}

	public Long getSatisfactionDegree() {
		return satisfactionDegree;
	}

	public void setSatisfactionDegree(Long satisfactionDegree) {
		this.satisfactionDegree = satisfactionDegree;
	}

	public String getSecondAssistant() {
		return secondAssistant;
	}

	public void setSecondAssistant(String secondAssistant) {
		this.secondAssistant = secondAssistant;
	}

	public String getSecondOperationNurse() {
		return secondOperationNurse;
	}

	public void setSecondOperationNurse(String secondOperationNurse) {
		this.secondOperationNurse = secondOperationNurse;
	}

	public String getSecondSupplyNurse() {
		return secondSupplyNurse;
	}

	public void setSecondSupplyNurse(String secondSupplyNurse) {
		this.secondSupplyNurse = secondSupplyNurse;
	}

	public Date getSendOutDate() {
		return sendOutDate;
	}

	public void setSendOutDate(Date sendOutDate) {
		this.sendOutDate = sendOutDate;
	}

	public Long getSequence() {
		return sequence;
	}

	public void setSequence(Long sequence) {
		this.sequence = sequence;
	}

	public Long getSmoothIndicator() {
		return smoothIndicator;
	}

	public void setSmoothIndicator(Long smoothIndicator) {
		this.smoothIndicator = smoothIndicator;
	}

	public Date getStartDateTime() {
		return startDateTime;
	}

	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	public String getSurgeon() {
		return surgeon;
	}

	public void setSurgeon(String surgeon) {
		this.surgeon = surgeon;
	}

	public String getThirdAssistant() {
		return thirdAssistant;
	}

	public void setThirdAssistant(String thirdAssistant) {
		this.thirdAssistant = thirdAssistant;
	}

	public String getThirdSupplyNurse() {
		return thirdSupplyNurse;
	}

	public void setThirdSupplyNurse(String thirdSupplyNurse) {
		this.thirdSupplyNurse = thirdSupplyNurse;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}
	
	
}