package com.hitzd.his.casehistory.beans.operation;

import java.util.Date;

/**
 * OperationName generated by MyEclipse Persistence Tools
 */

public class OperationName implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -7349933454465628862L;

	private String patientId;

	private Long visitId;

	private Long operId;

	private Long operationNo;

	private String operation;

	private String operationCode;

	private String operationScale;

	private String woundGrade;

	private Long serialNo;

	private Date linkDate;

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public String getOperationCode() {
		return operationCode;
	}

	public void setOperationCode(String operationCode) {
		this.operationCode = operationCode;
	}

	public Long getOperationNo() {
		return operationNo;
	}

	public void setOperationNo(Long operationNo) {
		this.operationNo = operationNo;
	}

	public String getOperationScale() {
		return operationScale;
	}

	public void setOperationScale(String operationScale) {
		this.operationScale = operationScale;
	}

	public Long getOperId() {
		return operId;
	}

	public void setOperId(Long operId) {
		this.operId = operId;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public Long getSerialNo() {
		return serialNo;
	}

	public void setSerialNo(Long serialNo) {
		this.serialNo = serialNo;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

	public String getWoundGrade() {
		return woundGrade;
	}

	public void setWoundGrade(String woundGrade) {
		this.woundGrade = woundGrade;
	}
	
}