package com.hitzd.his.casehistory.beans.labtest;

import java.util.Date;

/**
 * LabResult generated by MyEclipse Persistence Tools
 */

public class LabResult implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 2332169698223232603L;

	private String reportItemName;

	private String reportItemCode;

	private String result;

	private String units;

	private String abnormalIndicator;

	private String instrumentId;

	private Date resultDateTime;

	private String printContext;

	private Date linkDate;


	private String testNo;

	private Long itemNo;

	private Long printOrder;

	public String getAbnormalIndicator() {
		return abnormalIndicator;
	}

	public void setAbnormalIndicator(String abnormalIndicator) {
		this.abnormalIndicator = abnormalIndicator;
	}

	public String getInstrumentId() {
		return instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	public Long getItemNo() {
		return itemNo;
	}

	public void setItemNo(Long itemNo) {
		this.itemNo = itemNo;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getPrintContext() {
		return printContext;
	}

	public void setPrintContext(String printContext) {
		this.printContext = printContext;
	}

	public Long getPrintOrder() {
		return printOrder;
	}

	public void setPrintOrder(Long printOrder) {
		this.printOrder = printOrder;
	}

	public String getReportItemCode() {
		return reportItemCode;
	}

	public void setReportItemCode(String reportItemCode) {
		this.reportItemCode = reportItemCode;
	}

	public String getReportItemName() {
		return reportItemName;
	}

	public void setReportItemName(String reportItemName) {
		this.reportItemName = reportItemName;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public Date getResultDateTime() {
		return resultDateTime;
	}

	public void setResultDateTime(Date resultDateTime) {
		this.resultDateTime = resultDateTime;
	}

	public String getTestNo() {
		return testNo;
	}

	public void setTestNo(String testNo) {
		this.testNo = testNo;
	}

	public String getUnits() {
		return units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

}