package com.hitzd.his.casehistory.beans.labtest;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * LabTestMaster generated by MyEclipse Persistence Tools
 */

public class LabTestMaster implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 9072299359390213064L;

	private String testNo;

	private Long priorityIndicator;

	private String patientId;

	private Long visitId;

	private String workingId;

	private Date executeDate;

	private String name;

	private String namePhonetic;

	private String chargeType;

	private String sex;

	private Long age;

	private String testCause;

	private String relevantClinicDiag;

	private String specimen;

	private String notesForSpcm;

	private Date spcmReceivedDateTime;

	private Date spcmSampleDateTime;

	private Date requestedDateTime;

	private String orderingDept;

	private String orderingProvider;

	private String performedBy;

	private String resultStatus;

	private Date resultsRptDateTime;

	private String transcriptionist;

	private String verifiedBy;

	private Double costs;

	private Double charges;

	private Long billingIndicator;

	private Long printIndicator;

	private String subject;

	private String orderDeptName;

	private Long orderClinicAttr;

	private Long orderOutpOrInp;

	private Long orderInternalOrSergery;

	private String performDeptName;

	private Long performClinicAttr;

	private Long performOutpOrInp;

	private Long performInternalOrSergery;

	private Date linkDate;

	private List<LabTestItems> labTestItems = new ArrayList<LabTestItems>();
	public int getLabTestItemsCount()
	{
		return labTestItems.size();
	}
	public LabTestItems getLabTestItemsByIndex(int index)
	{
		return labTestItems.get(index);
	}
	public void addLabTestItems(LabTestItems value)
	{
		labTestItems.add(value);
	}
	public void removeLabTestItemsByIndex(int index)
	{
		labTestItems.remove(index);
	}
	private List<LabResult> labResults = new ArrayList<LabResult>();
	public int getLabResultCount()
	{
		return labResults.size();
	}
	public LabResult getLabResultByIndex(int index)
	{
		return labResults.get(index);
	}
	public void addLabResult(LabResult value)
	{
		labResults.add(value);
	}
	public void removeLabResultByIndex(int index)
	{
		labResults.remove(index);
	}
	
	public Long getAge() {
		return age;
	}

	public void setAge(Long age) {
		this.age = age;
	}

	public Long getBillingIndicator() {
		return billingIndicator;
	}

	public void setBillingIndicator(Long billingIndicator) {
		this.billingIndicator = billingIndicator;
	}

	public Double getCharges() {
		return charges;
	}

	public void setCharges(Double charges) {
		this.charges = charges;
	}

	public String getChargeType() {
		return chargeType;
	}

	public void setChargeType(String chargeType) {
		this.chargeType = chargeType;
	}

	public Double getCosts() {
		return costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

	public Date getExecuteDate() {
		return executeDate;
	}

	public void setExecuteDate(Date executeDate) {
		this.executeDate = executeDate;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNamePhonetic() {
		return namePhonetic;
	}

	public void setNamePhonetic(String namePhonetic) {
		this.namePhonetic = namePhonetic;
	}

	public String getNotesForSpcm() {
		return notesForSpcm;
	}

	public void setNotesForSpcm(String notesForSpcm) {
		this.notesForSpcm = notesForSpcm;
	}

	public Long getOrderClinicAttr() {
		return orderClinicAttr;
	}

	public void setOrderClinicAttr(Long orderClinicAttr) {
		this.orderClinicAttr = orderClinicAttr;
	}

	public String getOrderDeptName() {
		return orderDeptName;
	}

	public void setOrderDeptName(String orderDeptName) {
		this.orderDeptName = orderDeptName;
	}

	public String getOrderingDept() {
		return orderingDept;
	}

	public void setOrderingDept(String orderingDept) {
		this.orderingDept = orderingDept;
	}

	public String getOrderingProvider() {
		return orderingProvider;
	}

	public void setOrderingProvider(String orderingProvider) {
		this.orderingProvider = orderingProvider;
	}

	public Long getOrderInternalOrSergery() {
		return orderInternalOrSergery;
	}

	public void setOrderInternalOrSergery(Long orderInternalOrSergery) {
		this.orderInternalOrSergery = orderInternalOrSergery;
	}

	public Long getOrderOutpOrInp() {
		return orderOutpOrInp;
	}

	public void setOrderOutpOrInp(Long orderOutpOrInp) {
		this.orderOutpOrInp = orderOutpOrInp;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public Long getPerformClinicAttr() {
		return performClinicAttr;
	}

	public void setPerformClinicAttr(Long performClinicAttr) {
		this.performClinicAttr = performClinicAttr;
	}

	public String getPerformDeptName() {
		return performDeptName;
	}

	public void setPerformDeptName(String performDeptName) {
		this.performDeptName = performDeptName;
	}

	public String getPerformedBy() {
		return performedBy;
	}

	public void setPerformedBy(String performedBy) {
		this.performedBy = performedBy;
	}

	public Long getPerformInternalOrSergery() {
		return performInternalOrSergery;
	}

	public void setPerformInternalOrSergery(Long performInternalOrSergery) {
		this.performInternalOrSergery = performInternalOrSergery;
	}

	public Long getPerformOutpOrInp() {
		return performOutpOrInp;
	}

	public void setPerformOutpOrInp(Long performOutpOrInp) {
		this.performOutpOrInp = performOutpOrInp;
	}

	public Long getPrintIndicator() {
		return printIndicator;
	}

	public void setPrintIndicator(Long printIndicator) {
		this.printIndicator = printIndicator;
	}

	public Long getPriorityIndicator() {
		return priorityIndicator;
	}

	public void setPriorityIndicator(Long priorityIndicator) {
		this.priorityIndicator = priorityIndicator;
	}

	public String getRelevantClinicDiag() {
		return relevantClinicDiag;
	}

	public void setRelevantClinicDiag(String relevantClinicDiag) {
		this.relevantClinicDiag = relevantClinicDiag;
	}

	public Date getRequestedDateTime() {
		return requestedDateTime;
	}

	public void setRequestedDateTime(Date requestedDateTime) {
		this.requestedDateTime = requestedDateTime;
	}

	public Date getResultsRptDateTime() {
		return resultsRptDateTime;
	}

	public void setResultsRptDateTime(Date resultsRptDateTime) {
		this.resultsRptDateTime = resultsRptDateTime;
	}

	public String getResultStatus() {
		return resultStatus;
	}

	public void setResultStatus(String resultStatus) {
		this.resultStatus = resultStatus;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getSpcmReceivedDateTime() {
		return spcmReceivedDateTime;
	}

	public void setSpcmReceivedDateTime(Date spcmReceivedDateTime) {
		this.spcmReceivedDateTime = spcmReceivedDateTime;
	}

	public Date getSpcmSampleDateTime() {
		return spcmSampleDateTime;
	}

	public void setSpcmSampleDateTime(Date spcmSampleDateTime) {
		this.spcmSampleDateTime = spcmSampleDateTime;
	}

	public String getSpecimen() {
		return specimen;
	}

	public void setSpecimen(String specimen) {
		this.specimen = specimen;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getTestCause() {
		return testCause;
	}

	public void setTestCause(String testCause) {
		this.testCause = testCause;
	}

	public String getTestNo() {
		return testNo;
	}

	public void setTestNo(String testNo) {
		this.testNo = testNo;
	}

	public String getTranscriptionist() {
		return transcriptionist;
	}

	public void setTranscriptionist(String transcriptionist) {
		this.transcriptionist = transcriptionist;
	}

	public String getVerifiedBy() {
		return verifiedBy;
	}

	public void setVerifiedBy(String verifiedBy) {
		this.verifiedBy = verifiedBy;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

	public String getWorkingId() {
		return workingId;
	}

	public void setWorkingId(String workingId) {
		this.workingId = workingId;
	}
	
	
}