package com.hitzd.his.casehistory.beans.labtest;

import java.util.Date;

/**
 * LabTestItems generated by MyEclipse Persistence Tools
 */

public class LabTestItems implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -8135832337146862994L;

	private String itemName;

	private String itemCode;

	private Date linkDate;
	private String testNo;

	private Long itemNo;

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Long getItemNo() {
		return itemNo;
	}

	public void setItemNo(Long itemNo) {
		this.itemNo = itemNo;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getTestNo() {
		return testNo;
	}

	public void setTestNo(String testNo) {
		this.testNo = testNo;
	}
	
}