package com.hitzd.his.casehistory.beans.germtest;

import java.util.Date;

/**
 * DrugSensitResult generated by MyEclipse Persistence Tools
 */

public class DrugSensitResult implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 7695851197959371213L;

	private String germNo;

	private String antiNo;

	private String testResult;

	private Double testValue;

	private String vitekResult;

	private Date linkDate;

	private String testNo;

	private Long itemNo;

	public String getAntiNo() {
		return antiNo;
	}

	public void setAntiNo(String antiNo) {
		this.antiNo = antiNo;
	}

	public String getGermNo() {
		return germNo;
	}

	public void setGermNo(String germNo) {
		this.germNo = germNo;
	}

	public Long getItemNo() {
		return itemNo;
	}

	public void setItemNo(Long itemNo) {
		this.itemNo = itemNo;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getTestNo() {
		return testNo;
	}

	public void setTestNo(String testNo) {
		this.testNo = testNo;
	}

	public String getTestResult() {
		return testResult;
	}

	public void setTestResult(String testResult) {
		this.testResult = testResult;
	}

	public Double getTestValue() {
		return testValue;
	}

	public void setTestValue(Double testValue) {
		this.testValue = testValue;
	}

	public String getVitekResult() {
		return vitekResult;
	}

	public void setVitekResult(String vitekResult) {
		this.vitekResult = vitekResult;
	}

}