package com.hitzd.his.casehistory.beans.germtest;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * GermTest generated by MyEclipse Persistence Tools
 */

public class GermTest implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -3479939063887616378L;

	private String testNo;

	private String patientId;

	private Long visitId;

	private String orderingDept;

	private Date testDate;

	private String specimenType;

	private String itemCode;

	private String testMethod;

	private String enzymeAbduction;

	private String enzymeSpectrum;

	private String enzymeBeta;

	private String testResult;

	private Date spcmReceivedDate;

	private Date spcmCollectionDate;

	private Date cultureCompletionDate;

	private Long hoursPositive;

	private String cultureType;

	private String cultureCommentCode;

	private String name;

	private String sex;

	private Long age;

	private String deptName;

	private Long clinicAttr;

	private Long outpOrInp;

	private Long internalOrSergery;

	private Date linkDate;
	
	private List<DrugSensitResult> drugSensitResult = new ArrayList<DrugSensitResult>();
	public int getDrugSensitResultCount()
	{
		return drugSensitResult.size();
	}
	public DrugSensitResult getDrugSensitResultByIndex(int index)
	{
		return drugSensitResult.get(index);
	}
	public void addExamReport(DrugSensitResult value)
	{
		drugSensitResult.add(value);
	}
	public void removeDrugSensitResultByIndex(int index)
	{
		drugSensitResult.remove(index);
	}

	public Long getAge() {
		return age;
	}

	public void setAge(Long age) {
		this.age = age;
	}

	public Long getClinicAttr() {
		return clinicAttr;
	}

	public void setClinicAttr(Long clinicAttr) {
		this.clinicAttr = clinicAttr;
	}

	public String getCultureCommentCode() {
		return cultureCommentCode;
	}

	public void setCultureCommentCode(String cultureCommentCode) {
		this.cultureCommentCode = cultureCommentCode;
	}

	public Date getCultureCompletionDate() {
		return cultureCompletionDate;
	}

	public void setCultureCompletionDate(Date cultureCompletionDate) {
		this.cultureCompletionDate = cultureCompletionDate;
	}

	public String getCultureType() {
		return cultureType;
	}

	public void setCultureType(String cultureType) {
		this.cultureType = cultureType;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getEnzymeAbduction() {
		return enzymeAbduction;
	}

	public void setEnzymeAbduction(String enzymeAbduction) {
		this.enzymeAbduction = enzymeAbduction;
	}

	public String getEnzymeBeta() {
		return enzymeBeta;
	}

	public void setEnzymeBeta(String enzymeBeta) {
		this.enzymeBeta = enzymeBeta;
	}

	public String getEnzymeSpectrum() {
		return enzymeSpectrum;
	}

	public void setEnzymeSpectrum(String enzymeSpectrum) {
		this.enzymeSpectrum = enzymeSpectrum;
	}

	public Long getHoursPositive() {
		return hoursPositive;
	}

	public void setHoursPositive(Long hoursPositive) {
		this.hoursPositive = hoursPositive;
	}

	public Long getInternalOrSergery() {
		return internalOrSergery;
	}

	public void setInternalOrSergery(Long internalOrSergery) {
		this.internalOrSergery = internalOrSergery;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOrderingDept() {
		return orderingDept;
	}

	public void setOrderingDept(String orderingDept) {
		this.orderingDept = orderingDept;
	}

	public Long getOutpOrInp() {
		return outpOrInp;
	}

	public void setOutpOrInp(Long outpOrInp) {
		this.outpOrInp = outpOrInp;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getSpcmCollectionDate() {
		return spcmCollectionDate;
	}

	public void setSpcmCollectionDate(Date spcmCollectionDate) {
		this.spcmCollectionDate = spcmCollectionDate;
	}

	public Date getSpcmReceivedDate() {
		return spcmReceivedDate;
	}

	public void setSpcmReceivedDate(Date spcmReceivedDate) {
		this.spcmReceivedDate = spcmReceivedDate;
	}

	public String getSpecimenType() {
		return specimenType;
	}

	public void setSpecimenType(String specimenType) {
		this.specimenType = specimenType;
	}

	public Date getTestDate() {
		return testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	public String getTestMethod() {
		return testMethod;
	}

	public void setTestMethod(String testMethod) {
		this.testMethod = testMethod;
	}

	public String getTestNo() {
		return testNo;
	}

	public void setTestNo(String testNo) {
		this.testNo = testNo;
	}

	public String getTestResult() {
		return testResult;
	}

	public void setTestResult(String testResult) {
		this.testResult = testResult;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}
	
}