package com.hitzd.his.casehistory.beans.germtest;

import java.util.Date;

/**
 * GermTestResult generated by MyEclipse Persistence Tools
 */

public class GermTestResult implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -5585946959957326098L;

	private String testNo;

	private String patientId;

	private Long visitId;

	private String orderingDept;

	private Date testDate;

	private String specimenType;

	private String testResult;

	private String gramPosBac;

	private String gramNegBac;

	private String fungus;

	private String gramPosCoc;

	private String gramNegCoc;

	private String fusiformis;

	private String epithCell;

	private String whiteBCell;

	private String vaginaClear;

	private String gramPosBacDesc;

	private String gramPosNegDesc;

	private String fungusDesc;

	private String gramPosCocDesc;

	private String gramNegCocDesc;

	private String epithCellDesc;

	private String whiteBCellDesc;

	private String otherItemDesc;

	private String vaginaClearDesc;

	private String name;

	private String sex;

	private Long age;

	private String deptName;

	private Long clinicAttr;

	private Long outpOrInp;

	private Long internalOrSergery;

	private Date linkDate;

	public Long getAge() {
		return age;
	}

	public void setAge(Long age) {
		this.age = age;
	}

	public Long getClinicAttr() {
		return clinicAttr;
	}

	public void setClinicAttr(Long clinicAttr) {
		this.clinicAttr = clinicAttr;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getEpithCell() {
		return epithCell;
	}

	public void setEpithCell(String epithCell) {
		this.epithCell = epithCell;
	}

	public String getEpithCellDesc() {
		return epithCellDesc;
	}

	public void setEpithCellDesc(String epithCellDesc) {
		this.epithCellDesc = epithCellDesc;
	}

	public String getFungus() {
		return fungus;
	}

	public void setFungus(String fungus) {
		this.fungus = fungus;
	}

	public String getFungusDesc() {
		return fungusDesc;
	}

	public void setFungusDesc(String fungusDesc) {
		this.fungusDesc = fungusDesc;
	}

	public String getFusiformis() {
		return fusiformis;
	}

	public void setFusiformis(String fusiformis) {
		this.fusiformis = fusiformis;
	}

	public String getGramNegBac() {
		return gramNegBac;
	}

	public void setGramNegBac(String gramNegBac) {
		this.gramNegBac = gramNegBac;
	}

	public String getGramNegCoc() {
		return gramNegCoc;
	}

	public void setGramNegCoc(String gramNegCoc) {
		this.gramNegCoc = gramNegCoc;
	}

	public String getGramNegCocDesc() {
		return gramNegCocDesc;
	}

	public void setGramNegCocDesc(String gramNegCocDesc) {
		this.gramNegCocDesc = gramNegCocDesc;
	}

	public String getGramPosBac() {
		return gramPosBac;
	}

	public void setGramPosBac(String gramPosBac) {
		this.gramPosBac = gramPosBac;
	}

	public String getGramPosBacDesc() {
		return gramPosBacDesc;
	}

	public void setGramPosBacDesc(String gramPosBacDesc) {
		this.gramPosBacDesc = gramPosBacDesc;
	}

	public String getGramPosCoc() {
		return gramPosCoc;
	}

	public void setGramPosCoc(String gramPosCoc) {
		this.gramPosCoc = gramPosCoc;
	}

	public String getGramPosCocDesc() {
		return gramPosCocDesc;
	}

	public void setGramPosCocDesc(String gramPosCocDesc) {
		this.gramPosCocDesc = gramPosCocDesc;
	}

	public String getGramPosNegDesc() {
		return gramPosNegDesc;
	}

	public void setGramPosNegDesc(String gramPosNegDesc) {
		this.gramPosNegDesc = gramPosNegDesc;
	}

	public Long getInternalOrSergery() {
		return internalOrSergery;
	}

	public void setInternalOrSergery(Long internalOrSergery) {
		this.internalOrSergery = internalOrSergery;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOrderingDept() {
		return orderingDept;
	}

	public void setOrderingDept(String orderingDept) {
		this.orderingDept = orderingDept;
	}

	public String getOtherItemDesc() {
		return otherItemDesc;
	}

	public void setOtherItemDesc(String otherItemDesc) {
		this.otherItemDesc = otherItemDesc;
	}

	public Long getOutpOrInp() {
		return outpOrInp;
	}

	public void setOutpOrInp(Long outpOrInp) {
		this.outpOrInp = outpOrInp;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSpecimenType() {
		return specimenType;
	}

	public void setSpecimenType(String specimenType) {
		this.specimenType = specimenType;
	}

	public Date getTestDate() {
		return testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	public String getTestNo() {
		return testNo;
	}

	public void setTestNo(String testNo) {
		this.testNo = testNo;
	}

	public String getTestResult() {
		return testResult;
	}

	public void setTestResult(String testResult) {
		this.testResult = testResult;
	}

	public String getVaginaClear() {
		return vaginaClear;
	}

	public void setVaginaClear(String vaginaClear) {
		this.vaginaClear = vaginaClear;
	}

	public String getVaginaClearDesc() {
		return vaginaClearDesc;
	}

	public void setVaginaClearDesc(String vaginaClearDesc) {
		this.vaginaClearDesc = vaginaClearDesc;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

	public String getWhiteBCell() {
		return whiteBCell;
	}

	public void setWhiteBCell(String whiteBCell) {
		this.whiteBCell = whiteBCell;
	}

	public String getWhiteBCellDesc() {
		return whiteBCellDesc;
	}

	public void setWhiteBCellDesc(String whiteBCellDesc) {
		this.whiteBCellDesc = whiteBCellDesc;
	}
	
}