package com.hitzd.his.casehistory.beans.exam;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * ExamMaster generated by MyEclipse Persistence Tools
 */

public class ExamMaster implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String examNo;

	private String localIdClass;

	private String patientLocalId;

	private String patientId;

	private Long visitId;

	private String name;

	private String sex;

	private Date dateOfBirth;

	private Date spmRecvedDate;

	private String clinSymp;

	private String physSign;

	private String relevantLabTest;

	private String relevantDiag;

	private String clinDiag;

	private String device;

	private String performedBy;

	private String patientSource;

	private String facility;

	private Date reqDateTime;

	private String reqDept;

	private String reqPhysician;

	private String reqMemo;

	private Date scheduledDateTime;

	private String notice;

	private Date reportDateTime;

	private String technician;

	private String reporter;

	private String resultStatus;

	private Double costs;

	private Double charges;

	private Long chargeIndicator;

	private Long priorityIndicator;

	private String identity;

	private String chargeType;

	private String verifier;

	private String examReason;

	private String examMode;

	private String examGroup;

	private Date examDateTime;

	private String examClass;

	private String examSubClass;

	private String orderDeptName;

	private Long orderClinicAttr;

	private Long orderOutpOrInp;

	private Long orderInternalOrSergery;

	private String performDeptName;

	private Long performClinicAttr;

	private Long performOutpOrInp;

	private Long performInternalOrSergery;

	private Date linkDate;
	
	private List<ExamItems> examItems = new ArrayList<ExamItems>();
	public int getExamItemsCount()
	{
		return examItems.size();
	}
	public ExamItems getExamItemsByIndex(int index)
	{
		return examItems.get(index);
	}
	public void addExamItems(ExamItems value)
	{
		examItems.add(value);
	}
	public void removeExamItemsByIndex(int index)
	{
		examItems.remove(index);
	}
	private List<ExamReport> examReports = new ArrayList<ExamReport>();
	public int getExamReportCount()
	{
		return examReports.size();
	}
	public ExamReport getExamReportByIndex(int index)
	{
		return examReports.get(index);
	}
	public void addExamReport(ExamReport value)
	{
		examReports.add(value);
	}
	public void removeExamReportByIndex(int index)
	{
		examReports.remove(index);
	}

	public Long getChargeIndicator() {
		return chargeIndicator;
	}

	public void setChargeIndicator(Long chargeIndicator) {
		this.chargeIndicator = chargeIndicator;
	}

	public Double getCharges() {
		return charges;
	}

	public void setCharges(Double charges) {
		this.charges = charges;
	}

	public String getChargeType() {
		return chargeType;
	}

	public void setChargeType(String chargeType) {
		this.chargeType = chargeType;
	}

	public String getClinDiag() {
		return clinDiag;
	}

	public void setClinDiag(String clinDiag) {
		this.clinDiag = clinDiag;
	}

	public String getClinSymp() {
		return clinSymp;
	}

	public void setClinSymp(String clinSymp) {
		this.clinSymp = clinSymp;
	}

	public Double getCosts() {
		return costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getDevice() {
		return device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public String getExamClass() {
		return examClass;
	}

	public void setExamClass(String examClass) {
		this.examClass = examClass;
	}

	public Date getExamDateTime() {
		return examDateTime;
	}

	public void setExamDateTime(Date examDateTime) {
		this.examDateTime = examDateTime;
	}

	public String getExamGroup() {
		return examGroup;
	}

	public void setExamGroup(String examGroup) {
		this.examGroup = examGroup;
	}

	public String getExamMode() {
		return examMode;
	}

	public void setExamMode(String examMode) {
		this.examMode = examMode;
	}

	public String getExamNo() {
		return examNo;
	}

	public void setExamNo(String examNo) {
		this.examNo = examNo;
	}

	public String getExamReason() {
		return examReason;
	}

	public void setExamReason(String examReason) {
		this.examReason = examReason;
	}

	public String getExamSubClass() {
		return examSubClass;
	}

	public void setExamSubClass(String examSubClass) {
		this.examSubClass = examSubClass;
	}

	public String getFacility() {
		return facility;
	}

	public void setFacility(String facility) {
		this.facility = facility;
	}

	public String getIdentity() {
		return identity;
	}

	public void setIdentity(String identity) {
		this.identity = identity;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getLocalIdClass() {
		return localIdClass;
	}

	public void setLocalIdClass(String localIdClass) {
		this.localIdClass = localIdClass;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNotice() {
		return notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public Long getOrderClinicAttr() {
		return orderClinicAttr;
	}

	public void setOrderClinicAttr(Long orderClinicAttr) {
		this.orderClinicAttr = orderClinicAttr;
	}

	public String getOrderDeptName() {
		return orderDeptName;
	}

	public void setOrderDeptName(String orderDeptName) {
		this.orderDeptName = orderDeptName;
	}

	public Long getOrderInternalOrSergery() {
		return orderInternalOrSergery;
	}

	public void setOrderInternalOrSergery(Long orderInternalOrSergery) {
		this.orderInternalOrSergery = orderInternalOrSergery;
	}

	public Long getOrderOutpOrInp() {
		return orderOutpOrInp;
	}

	public void setOrderOutpOrInp(Long orderOutpOrInp) {
		this.orderOutpOrInp = orderOutpOrInp;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getPatientLocalId() {
		return patientLocalId;
	}

	public void setPatientLocalId(String patientLocalId) {
		this.patientLocalId = patientLocalId;
	}

	public String getPatientSource() {
		return patientSource;
	}

	public void setPatientSource(String patientSource) {
		this.patientSource = patientSource;
	}

	public Long getPerformClinicAttr() {
		return performClinicAttr;
	}

	public void setPerformClinicAttr(Long performClinicAttr) {
		this.performClinicAttr = performClinicAttr;
	}

	public String getPerformDeptName() {
		return performDeptName;
	}

	public void setPerformDeptName(String performDeptName) {
		this.performDeptName = performDeptName;
	}

	public String getPerformedBy() {
		return performedBy;
	}

	public void setPerformedBy(String performedBy) {
		this.performedBy = performedBy;
	}

	public Long getPerformInternalOrSergery() {
		return performInternalOrSergery;
	}

	public void setPerformInternalOrSergery(Long performInternalOrSergery) {
		this.performInternalOrSergery = performInternalOrSergery;
	}

	public Long getPerformOutpOrInp() {
		return performOutpOrInp;
	}

	public void setPerformOutpOrInp(Long performOutpOrInp) {
		this.performOutpOrInp = performOutpOrInp;
	}

	public String getPhysSign() {
		return physSign;
	}

	public void setPhysSign(String physSign) {
		this.physSign = physSign;
	}

	public Long getPriorityIndicator() {
		return priorityIndicator;
	}

	public void setPriorityIndicator(Long priorityIndicator) {
		this.priorityIndicator = priorityIndicator;
	}

	public String getRelevantDiag() {
		return relevantDiag;
	}

	public void setRelevantDiag(String relevantDiag) {
		this.relevantDiag = relevantDiag;
	}

	public String getRelevantLabTest() {
		return relevantLabTest;
	}

	public void setRelevantLabTest(String relevantLabTest) {
		this.relevantLabTest = relevantLabTest;
	}

	public Date getReportDateTime() {
		return reportDateTime;
	}

	public void setReportDateTime(Date reportDateTime) {
		this.reportDateTime = reportDateTime;
	}

	public String getReporter() {
		return reporter;
	}

	public void setReporter(String reporter) {
		this.reporter = reporter;
	}

	public Date getReqDateTime() {
		return reqDateTime;
	}

	public void setReqDateTime(Date reqDateTime) {
		this.reqDateTime = reqDateTime;
	}

	public String getReqDept() {
		return reqDept;
	}

	public void setReqDept(String reqDept) {
		this.reqDept = reqDept;
	}

	public String getReqMemo() {
		return reqMemo;
	}

	public void setReqMemo(String reqMemo) {
		this.reqMemo = reqMemo;
	}

	public String getReqPhysician() {
		return reqPhysician;
	}

	public void setReqPhysician(String reqPhysician) {
		this.reqPhysician = reqPhysician;
	}

	public String getResultStatus() {
		return resultStatus;
	}

	public void setResultStatus(String resultStatus) {
		this.resultStatus = resultStatus;
	}

	public Date getScheduledDateTime() {
		return scheduledDateTime;
	}

	public void setScheduledDateTime(Date scheduledDateTime) {
		this.scheduledDateTime = scheduledDateTime;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getSpmRecvedDate() {
		return spmRecvedDate;
	}

	public void setSpmRecvedDate(Date spmRecvedDate) {
		this.spmRecvedDate = spmRecvedDate;
	}

	public String getTechnician() {
		return technician;
	}

	public void setTechnician(String technician) {
		this.technician = technician;
	}

	public String getVerifier() {
		return verifier;
	}

	public void setVerifier(String verifier) {
		this.verifier = verifier;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}
}