package com.hitzd.his.casehistory.beans.exam;

import java.util.Date;

/**
 * ExamItems generated by MyEclipse Persistence Tools
 */

public class ExamItems implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	// Fields
	private String examNo;

	private Long examItemNo;

	private String examItem;

	private String examItemCode;

	private Double costs;

	private Date linkDate;

	public Double getCosts() {
		return costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

	public String getExamItem() {
		return examItem;
	}

	public void setExamItem(String examItem) {
		this.examItem = examItem;
	}

	public String getExamItemCode() {
		return examItemCode;
	}

	public void setExamItemCode(String examItemCode) {
		this.examItemCode = examItemCode;
	}

	public Long getExamItemNo() {
		return examItemNo;
	}

	public void setExamItemNo(Long examItemNo) {
		this.examItemNo = examItemNo;
	}

	public String getExamNo() {
		return examNo;
	}

	public void setExamNo(String examNo) {
		this.examNo = examNo;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}


}