package com.hitzd.his.casehistory.beans.exam;

import java.util.Date;

/**
 * ExamReport generated by MyEclipse Persistence Tools
 */

public class ExamReport implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String examNo;

	private String examPara;

	private String description;

	private String impression;

	private String recommendation;

	private String isAbnormal;

	private String useImage;

	private String memo;

	private String device;

	private Date linkDate;

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDevice() {
		return device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public String getExamNo() {
		return examNo;
	}

	public void setExamNo(String examNo) {
		this.examNo = examNo;
	}

	public String getExamPara() {
		return examPara;
	}

	public void setExamPara(String examPara) {
		this.examPara = examPara;
	}

	public String getImpression() {
		return impression;
	}

	public void setImpression(String impression) {
		this.impression = impression;
	}

	public String getIsAbnormal() {
		return isAbnormal;
	}

	public void setIsAbnormal(String isAbnormal) {
		this.isAbnormal = isAbnormal;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getRecommendation() {
		return recommendation;
	}

	public void setRecommendation(String recommendation) {
		this.recommendation = recommendation;
	}

	public String getUseImage() {
		return useImage;
	}

	public void setUseImage(String useImage) {
		this.useImage = useImage;
	}
	
	
}