package com.hitzd.his.casehistory.beans;

import java.util.Date;

/**
 * Diagnosis generated by MyEclipse Persistence Tools
 */

public class Diagnosis implements java.io.Serializable {

	// Fields


	/**
	 * 
	 */
	private static final long serialVersionUID = 5016294795369929397L;

	private String diagnosisDesc;

	private Date diagnosisDate;

	private Long treatDays;

	private String treatResult;

	private Long operTreatIndicator;

	private String basicDiag;

	private String diagnosisCode;

	private Date linkDate;
	
	private String patientId;

	private Long visitId;

	private String diagnosisType;

	private Long diagnosisNo;

	public String getBasicDiag() {
		return basicDiag;
	}

	public void setBasicDiag(String basicDiag) {
		this.basicDiag = basicDiag;
	}

	public String getDiagnosisCode() {
		return diagnosisCode;
	}

	public void setDiagnosisCode(String diagnosisCode) {
		this.diagnosisCode = diagnosisCode;
	}

	public Date getDiagnosisDate() {
		return diagnosisDate;
	}

	public void setDiagnosisDate(Date diagnosisDate) {
		this.diagnosisDate = diagnosisDate;
	}

	public String getDiagnosisDesc() {
		return diagnosisDesc;
	}

	public void setDiagnosisDesc(String diagnosisDesc) {
		this.diagnosisDesc = diagnosisDesc;
	}

	public Long getDiagnosisNo() {
		return diagnosisNo;
	}

	public void setDiagnosisNo(Long diagnosisNo) {
		this.diagnosisNo = diagnosisNo;
	}

	public String getDiagnosisType() {
		return diagnosisType;
	}

	public void setDiagnosisType(String diagnosisType) {
		this.diagnosisType = diagnosisType;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public Long getOperTreatIndicator() {
		return operTreatIndicator;
	}

	public void setOperTreatIndicator(Long operTreatIndicator) {
		this.operTreatIndicator = operTreatIndicator;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public Long getTreatDays() {
		return treatDays;
	}

	public void setTreatDays(Long treatDays) {
		this.treatDays = treatDays;
	}

	public String getTreatResult() {
		return treatResult;
	}

	public void setTreatResult(String treatResult) {
		this.treatResult = treatResult;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

}