package com.hitzd.his.casehistory.beans;

import java.util.Date;

/**
 * DrugDispenseRec generated by MyEclipse Persistence Tools
 */

public class DrugDispenseRec implements java.io.Serializable {

	// Fields


	/**
	 * 
	 */
	private static final long serialVersionUID = -2717103623158427055L;

	private String dispensary;

	private String orderedBy;

	private String drugCode;

	private String drugSpec;

	private String drugUnits;

	private String firmId;

	private Long dispenseAmount;

	private String dispensingProvider;

	private Double costs;

	private Double charges;

	private Long chargeIndicator;

	private String deptName;

	private Long clinicAttr;

	private Long outpOrInp;

	private Long internalOrSergery;

	private Date linkDate;

	private String isAnti;

	private String patientId;

	private Long visitId;

	private Long orderNo;

	private Long orderSubNo;

	private Date dispensingDateTime;

	public Long getChargeIndicator() {
		return chargeIndicator;
	}

	public void setChargeIndicator(Long chargeIndicator) {
		this.chargeIndicator = chargeIndicator;
	}

	public Double getCharges() {
		return charges;
	}

	public void setCharges(Double charges) {
		this.charges = charges;
	}

	public Long getClinicAttr() {
		return clinicAttr;
	}

	public void setClinicAttr(Long clinicAttr) {
		this.clinicAttr = clinicAttr;
	}

	public Double getCosts() {
		return costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDispensary() {
		return dispensary;
	}

	public void setDispensary(String dispensary) {
		this.dispensary = dispensary;
	}

	public Long getDispenseAmount() {
		return dispenseAmount;
	}

	public void setDispenseAmount(Long dispenseAmount) {
		this.dispenseAmount = dispenseAmount;
	}

	public Date getDispensingDateTime() {
		return dispensingDateTime;
	}

	public void setDispensingDateTime(Date dispensingDateTime) {
		this.dispensingDateTime = dispensingDateTime;
	}

	public String getDispensingProvider() {
		return dispensingProvider;
	}

	public void setDispensingProvider(String dispensingProvider) {
		this.dispensingProvider = dispensingProvider;
	}

	public String getDrugCode() {
		return drugCode;
	}

	public void setDrugCode(String drugCode) {
		this.drugCode = drugCode;
	}

	public String getDrugSpec() {
		return drugSpec;
	}

	public void setDrugSpec(String drugSpec) {
		this.drugSpec = drugSpec;
	}

	public String getDrugUnits() {
		return drugUnits;
	}

	public void setDrugUnits(String drugUnits) {
		this.drugUnits = drugUnits;
	}

	public String getFirmId() {
		return firmId;
	}

	public void setFirmId(String firmId) {
		this.firmId = firmId;
	}

	public Long getInternalOrSergery() {
		return internalOrSergery;
	}

	public void setInternalOrSergery(Long internalOrSergery) {
		this.internalOrSergery = internalOrSergery;
	}

	public String getIsAnti() {
		return isAnti;
	}

	public void setIsAnti(String isAnti) {
		this.isAnti = isAnti;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getOrderedBy() {
		return orderedBy;
	}

	public void setOrderedBy(String orderedBy) {
		this.orderedBy = orderedBy;
	}

	public Long getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	public Long getOrderSubNo() {
		return orderSubNo;
	}

	public void setOrderSubNo(Long orderSubNo) {
		this.orderSubNo = orderSubNo;
	}

	public Long getOutpOrInp() {
		return outpOrInp;
	}

	public void setOutpOrInp(Long outpOrInp) {
		this.outpOrInp = outpOrInp;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}
}