package com.hitzd.his.casehistory.beans;

import java.util.Date;

/**
 * InpBillDetail generated by MyEclipse Persistence Tools
 */

public class InpBillDetail implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 5120695969515709635L;

	private String itemClass;

	private String itemName;

	private String itemCode;

	private String itemSpec;

	private Double amount;

	private String units;

	private String orderedBy;

	private String performedBy;

	private Double costs;

	private Double charges;

	private Date billingDateTime;

	private String operatorNo;

	private String rcptNo;

	private Double specialCharges;

	private Double freeLimit;

	private String orderDeptName;

	private Long orderClinicAttr;

	private Long orderOutpOrInp;

	private Long orderInternalOrSergery;

	private String performDeptName;

	private Long performClinicAttr;

	private Long performOutpOrInp;

	private Long performInternalOrSergery;

	private Date linkDate;


	private String patientId;

	private Long visitId;

	private Long itemNo;

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Date getBillingDateTime() {
		return billingDateTime;
	}

	public void setBillingDateTime(Date billingDateTime) {
		this.billingDateTime = billingDateTime;
	}

	public Double getCharges() {
		return charges;
	}

	public void setCharges(Double charges) {
		this.charges = charges;
	}

	public Double getCosts() {
		return costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

	public Double getFreeLimit() {
		return freeLimit;
	}

	public void setFreeLimit(Double freeLimit) {
		this.freeLimit = freeLimit;
	}

	public String getItemClass() {
		return itemClass;
	}

	public void setItemClass(String itemClass) {
		this.itemClass = itemClass;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Long getItemNo() {
		return itemNo;
	}

	public void setItemNo(Long itemNo) {
		this.itemNo = itemNo;
	}

	public String getItemSpec() {
		return itemSpec;
	}

	public void setItemSpec(String itemSpec) {
		this.itemSpec = itemSpec;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getOperatorNo() {
		return operatorNo;
	}

	public void setOperatorNo(String operatorNo) {
		this.operatorNo = operatorNo;
	}

	public Long getOrderClinicAttr() {
		return orderClinicAttr;
	}

	public void setOrderClinicAttr(Long orderClinicAttr) {
		this.orderClinicAttr = orderClinicAttr;
	}

	public String getOrderDeptName() {
		return orderDeptName;
	}

	public void setOrderDeptName(String orderDeptName) {
		this.orderDeptName = orderDeptName;
	}

	public String getOrderedBy() {
		return orderedBy;
	}

	public void setOrderedBy(String orderedBy) {
		this.orderedBy = orderedBy;
	}

	public Long getOrderInternalOrSergery() {
		return orderInternalOrSergery;
	}

	public void setOrderInternalOrSergery(Long orderInternalOrSergery) {
		this.orderInternalOrSergery = orderInternalOrSergery;
	}

	public Long getOrderOutpOrInp() {
		return orderOutpOrInp;
	}

	public void setOrderOutpOrInp(Long orderOutpOrInp) {
		this.orderOutpOrInp = orderOutpOrInp;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public Long getPerformClinicAttr() {
		return performClinicAttr;
	}

	public void setPerformClinicAttr(Long performClinicAttr) {
		this.performClinicAttr = performClinicAttr;
	}

	public String getPerformDeptName() {
		return performDeptName;
	}

	public void setPerformDeptName(String performDeptName) {
		this.performDeptName = performDeptName;
	}

	public String getPerformedBy() {
		return performedBy;
	}

	public void setPerformedBy(String performedBy) {
		this.performedBy = performedBy;
	}

	public Long getPerformInternalOrSergery() {
		return performInternalOrSergery;
	}

	public void setPerformInternalOrSergery(Long performInternalOrSergery) {
		this.performInternalOrSergery = performInternalOrSergery;
	}

	public Long getPerformOutpOrInp() {
		return performOutpOrInp;
	}

	public void setPerformOutpOrInp(Long performOutpOrInp) {
		this.performOutpOrInp = performOutpOrInp;
	}

	public String getRcptNo() {
		return rcptNo;
	}

	public void setRcptNo(String rcptNo) {
		this.rcptNo = rcptNo;
	}

	public Double getSpecialCharges() {
		return specialCharges;
	}

	public void setSpecialCharges(Double specialCharges) {
		this.specialCharges = specialCharges;
	}

	public String getUnits() {
		return units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}
	
	
}