package com.hitzd.his.casehistory.beans;

import java.util.Date;

/**
 * Orders generated by MyEclipse Persistence Tools
 */

public class Orders implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -1951667812763530841L;

	private String patientId;

	private Long visitId;

	private Long orderNo;

	private Long orderSubNo;

	private Long repeatIndicator;

	private String orderClass;

	private String orderText;

	private String orderCode;

	private Double dosage;

	private String dosageUnits;

	private String administration;

	private Long duration;

	private String durationUnits;

	private Date startDateTime;

	private Date stopDateTime;

	private String frequency;

	private Long freqCounter;

	private Long freqInterval;

	private String freqIntervalUnit;

	private String freqDetail;

	private String performSchedule;

	private String performResult;

	private String orderingDept;

	private String doctor;

	private String stopDoctor;

	private String nurse;

	private Date enterDateTime;

	private String orderStatus;

	private Long billingAttr;

	private Date lastPerformDateTime;

	private Date lastAcctingDateTime;

	private String treatSheetFlag;

	private String phamStdCode;

	private Long amount;

	private Long drugBillingAttr;

	private String stopNurse;

	private Date stopOrderDateTime;

	private String deptName;

	private Long clinicAttr;

	private Long outpOrInp;

	private Long internalOrSergery;

	private Date linkDate;

	private Long dddValue;

	public String getAdministration() {
		return administration;
	}

	public void setAdministration(String administration) {
		this.administration = administration;
	}

	public Long getAmount() {
		return amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	public Long getBillingAttr() {
		return billingAttr;
	}

	public void setBillingAttr(Long billingAttr) {
		this.billingAttr = billingAttr;
	}

	public Long getClinicAttr() {
		return clinicAttr;
	}

	public void setClinicAttr(Long clinicAttr) {
		this.clinicAttr = clinicAttr;
	}

	public Long getDddValue() {
		return dddValue;
	}

	public void setDddValue(Long dddValue) {
		this.dddValue = dddValue;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDoctor() {
		return doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

	public Double getDosage() {
		return dosage;
	}

	public void setDosage(Double dosage) {
		this.dosage = dosage;
	}

	public String getDosageUnits() {
		return dosageUnits;
	}

	public void setDosageUnits(String dosageUnits) {
		this.dosageUnits = dosageUnits;
	}

	public Long getDrugBillingAttr() {
		return drugBillingAttr;
	}

	public void setDrugBillingAttr(Long drugBillingAttr) {
		this.drugBillingAttr = drugBillingAttr;
	}

	public Long getDuration() {
		return duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

	public String getDurationUnits() {
		return durationUnits;
	}

	public void setDurationUnits(String durationUnits) {
		this.durationUnits = durationUnits;
	}

	public Date getEnterDateTime() {
		return enterDateTime;
	}

	public void setEnterDateTime(Date enterDateTime) {
		this.enterDateTime = enterDateTime;
	}

	public Long getFreqCounter() {
		return freqCounter;
	}

	public void setFreqCounter(Long freqCounter) {
		this.freqCounter = freqCounter;
	}

	public String getFreqDetail() {
		return freqDetail;
	}

	public void setFreqDetail(String freqDetail) {
		this.freqDetail = freqDetail;
	}

	public Long getFreqInterval() {
		return freqInterval;
	}

	public void setFreqInterval(Long freqInterval) {
		this.freqInterval = freqInterval;
	}

	public String getFreqIntervalUnit() {
		return freqIntervalUnit;
	}

	public void setFreqIntervalUnit(String freqIntervalUnit) {
		this.freqIntervalUnit = freqIntervalUnit;
	}

	public String getFrequency() {
		return frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	public Long getInternalOrSergery() {
		return internalOrSergery;
	}

	public void setInternalOrSergery(Long internalOrSergery) {
		this.internalOrSergery = internalOrSergery;
	}

	public Date getLastAcctingDateTime() {
		return lastAcctingDateTime;
	}

	public void setLastAcctingDateTime(Date lastAcctingDateTime) {
		this.lastAcctingDateTime = lastAcctingDateTime;
	}

	public Date getLastPerformDateTime() {
		return lastPerformDateTime;
	}

	public void setLastPerformDateTime(Date lastPerformDateTime) {
		this.lastPerformDateTime = lastPerformDateTime;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getNurse() {
		return nurse;
	}

	public void setNurse(String nurse) {
		this.nurse = nurse;
	}

	public String getOrderClass() {
		return orderClass;
	}

	public void setOrderClass(String orderClass) {
		this.orderClass = orderClass;
	}

	public String getOrderCode() {
		return orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	public String getOrderingDept() {
		return orderingDept;
	}

	public void setOrderingDept(String orderingDept) {
		this.orderingDept = orderingDept;
	}

	public Long getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	public String getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Long getOrderSubNo() {
		return orderSubNo;
	}

	public void setOrderSubNo(Long orderSubNo) {
		this.orderSubNo = orderSubNo;
	}

	public String getOrderText() {
		return orderText;
	}

	public void setOrderText(String orderText) {
		this.orderText = orderText;
	}

	public Long getOutpOrInp() {
		return outpOrInp;
	}

	public void setOutpOrInp(Long outpOrInp) {
		this.outpOrInp = outpOrInp;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getPerformResult() {
		return performResult;
	}

	public void setPerformResult(String performResult) {
		this.performResult = performResult;
	}

	public String getPerformSchedule() {
		return performSchedule;
	}

	public void setPerformSchedule(String performSchedule) {
		this.performSchedule = performSchedule;
	}

	public String getPhamStdCode() {
		return phamStdCode;
	}

	public void setPhamStdCode(String phamStdCode) {
		this.phamStdCode = phamStdCode;
	}

	public Long getRepeatIndicator() {
		return repeatIndicator;
	}

	public void setRepeatIndicator(Long repeatIndicator) {
		this.repeatIndicator = repeatIndicator;
	}

	public Date getStartDateTime() {
		return startDateTime;
	}

	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	public Date getStopDateTime() {
		return stopDateTime;
	}

	public void setStopDateTime(Date stopDateTime) {
		this.stopDateTime = stopDateTime;
	}

	public String getStopDoctor() {
		return stopDoctor;
	}

	public void setStopDoctor(String stopDoctor) {
		this.stopDoctor = stopDoctor;
	}

	public String getStopNurse() {
		return stopNurse;
	}

	public void setStopNurse(String stopNurse) {
		this.stopNurse = stopNurse;
	}

	public Date getStopOrderDateTime() {
		return stopOrderDateTime;
	}

	public void setStopOrderDateTime(Date stopOrderDateTime) {
		this.stopOrderDateTime = stopOrderDateTime;
	}

	public String getTreatSheetFlag() {
		return treatSheetFlag;
	}

	public void setTreatSheetFlag(String treatSheetFlag) {
		this.treatSheetFlag = treatSheetFlag;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}
	
	
}