package com.hitzd.his.casehistory.beans;

import java.util.Date;

/**
 * PatMasterIndex generated by MyEclipse Persistence Tools
 */

public class PatMasterIndex implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -3344174437491660210L;

	private String patientId;

	private String inpNo;

	private String name;

	private String namePhonetic;

	private String sex;

	private Date dateOfBirth;

	private String birthPlace;

	private String citizenship;

	private String nation;

	private String idNo;

	private String identity;

	private String chargeType;

	private String unitInContract;

	private String mailingAddress;

	private String zipCode;

	private String phoneNumberHome;

	private String phoneNumberBusiness;

	private String nextOfKin;

	private String relationship;

	private String nextOfKinAddr;

	private String nextOfKinZipCode;

	private String nextOfKinPhone;

	private Date lastVisitDate;

	private Long vipIndicator;

	private Date createDate;

	private String operator;

	private String insuranceId;

	private String insuranceCardNo;

	private String insuranceIdNo;

	private Date linkDate;
	
	private PatVisit patVisit;

	public String getBirthPlace() 
	{
		return birthPlace;
	}

	public PatVisit getPatVisit() {
		return patVisit;
	}

	public void setPatVisit(PatVisit patVisit) {
		this.patVisit = patVisit;
	}

	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace;
	}

	public String getChargeType() {
		return chargeType;
	}

	public void setChargeType(String chargeType) {
		this.chargeType = chargeType;
	}

	public String getCitizenship() {
		return citizenship;
	}

	public void setCitizenship(String citizenship) {
		this.citizenship = citizenship;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getIdentity() {
		return identity;
	}

	public void setIdentity(String identity) {
		this.identity = identity;
	}

	public String getIdNo() {
		return idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	public String getInpNo() {
		return inpNo;
	}

	public void setInpNo(String inpNo) {
		this.inpNo = inpNo;
	}

	public String getInsuranceCardNo() {
		return insuranceCardNo;
	}

	public void setInsuranceCardNo(String insuranceCardNo) {
		this.insuranceCardNo = insuranceCardNo;
	}

	public String getInsuranceId() {
		return insuranceId;
	}

	public void setInsuranceId(String insuranceId) {
		this.insuranceId = insuranceId;
	}

	public String getInsuranceIdNo() {
		return insuranceIdNo;
	}

	public void setInsuranceIdNo(String insuranceIdNo) {
		this.insuranceIdNo = insuranceIdNo;
	}

	public Date getLastVisitDate() {
		return lastVisitDate;
	}

	public void setLastVisitDate(Date lastVisitDate) {
		this.lastVisitDate = lastVisitDate;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getMailingAddress() {
		return mailingAddress;
	}

	public void setMailingAddress(String mailingAddress) {
		this.mailingAddress = mailingAddress;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNamePhonetic() {
		return namePhonetic;
	}

	public void setNamePhonetic(String namePhonetic) {
		this.namePhonetic = namePhonetic;
	}

	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getNextOfKin() {
		return nextOfKin;
	}

	public void setNextOfKin(String nextOfKin) {
		this.nextOfKin = nextOfKin;
	}

	public String getNextOfKinAddr() {
		return nextOfKinAddr;
	}

	public void setNextOfKinAddr(String nextOfKinAddr) {
		this.nextOfKinAddr = nextOfKinAddr;
	}

	public String getNextOfKinPhone() {
		return nextOfKinPhone;
	}

	public void setNextOfKinPhone(String nextOfKinPhone) {
		this.nextOfKinPhone = nextOfKinPhone;
	}

	public String getNextOfKinZipCode() {
		return nextOfKinZipCode;
	}

	public void setNextOfKinZipCode(String nextOfKinZipCode) {
		this.nextOfKinZipCode = nextOfKinZipCode;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getPhoneNumberBusiness() {
		return phoneNumberBusiness;
	}

	public void setPhoneNumberBusiness(String phoneNumberBusiness) {
		this.phoneNumberBusiness = phoneNumberBusiness;
	}

	public String getPhoneNumberHome() {
		return phoneNumberHome;
	}

	public void setPhoneNumberHome(String phoneNumberHome) {
		this.phoneNumberHome = phoneNumberHome;
	}

	public String getRelationship() {
		return relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getUnitInContract() {
		return unitInContract;
	}

	public void setUnitInContract(String unitInContract) {
		this.unitInContract = unitInContract;
	}

	public Long getVipIndicator() {
		return vipIndicator;
	}

	public void setVipIndicator(Long vipIndicator) {
		this.vipIndicator = vipIndicator;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}
	
	
}