package com.hitzd.his.casehistory.beans;

import java.util.Date;

/**
 * PatsInHospital generated by MyEclipse Persistence Tools
 */

public class PatsInHospital implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 409858133750377494L;

	private String patientId;

	private Long visitId;

	private String wardCode;

	private String deptCode;

	private Long bedNo;

	private Date admissionDateTime;

	private Date admWardDateTime;

	private String diagnosis;

	private String patientCondition;

	private String nursingClass;

	private String doctorInCharge;

	private Date operatingDate;

	private Date billingDateTime;

	private Double prepayments;

	private Double totalCosts;

	private Double totalCharges;

	private String guarantor;

	private String guarantorOrg;

	private String guarantorPhoneNum;

	private Date billCheckedDateTime;

	private Long settledIndicator;

	private String deptName;

	private Long clinicAttr;

	private Long outpOrInp;

	private Long internalOrSergery;

	private Date linkDate;

	public Date getAdmissionDateTime() {
		return admissionDateTime;
	}

	public void setAdmissionDateTime(Date admissionDateTime) {
		this.admissionDateTime = admissionDateTime;
	}

	public Date getAdmWardDateTime() {
		return admWardDateTime;
	}

	public void setAdmWardDateTime(Date admWardDateTime) {
		this.admWardDateTime = admWardDateTime;
	}

	public Long getBedNo() {
		return bedNo;
	}

	public void setBedNo(Long bedNo) {
		this.bedNo = bedNo;
	}

	public Date getBillCheckedDateTime() {
		return billCheckedDateTime;
	}

	public void setBillCheckedDateTime(Date billCheckedDateTime) {
		this.billCheckedDateTime = billCheckedDateTime;
	}

	public Date getBillingDateTime() {
		return billingDateTime;
	}

	public void setBillingDateTime(Date billingDateTime) {
		this.billingDateTime = billingDateTime;
	}

	public Long getClinicAttr() {
		return clinicAttr;
	}

	public void setClinicAttr(Long clinicAttr) {
		this.clinicAttr = clinicAttr;
	}

	public String getDeptCode() {
		return deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDiagnosis() {
		return diagnosis;
	}

	public void setDiagnosis(String diagnosis) {
		this.diagnosis = diagnosis;
	}

	public String getDoctorInCharge() {
		return doctorInCharge;
	}

	public void setDoctorInCharge(String doctorInCharge) {
		this.doctorInCharge = doctorInCharge;
	}

	public String getGuarantor() {
		return guarantor;
	}

	public void setGuarantor(String guarantor) {
		this.guarantor = guarantor;
	}

	public String getGuarantorOrg() {
		return guarantorOrg;
	}

	public void setGuarantorOrg(String guarantorOrg) {
		this.guarantorOrg = guarantorOrg;
	}

	public String getGuarantorPhoneNum() {
		return guarantorPhoneNum;
	}

	public void setGuarantorPhoneNum(String guarantorPhoneNum) {
		this.guarantorPhoneNum = guarantorPhoneNum;
	}

	public Long getInternalOrSergery() {
		return internalOrSergery;
	}

	public void setInternalOrSergery(Long internalOrSergery) {
		this.internalOrSergery = internalOrSergery;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getNursingClass() {
		return nursingClass;
	}

	public void setNursingClass(String nursingClass) {
		this.nursingClass = nursingClass;
	}

	public Date getOperatingDate() {
		return operatingDate;
	}

	public void setOperatingDate(Date operatingDate) {
		this.operatingDate = operatingDate;
	}

	public Long getOutpOrInp() {
		return outpOrInp;
	}

	public void setOutpOrInp(Long outpOrInp) {
		this.outpOrInp = outpOrInp;
	}

	public String getPatientCondition() {
		return patientCondition;
	}

	public void setPatientCondition(String patientCondition) {
		this.patientCondition = patientCondition;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public Double getPrepayments() {
		return prepayments;
	}

	public void setPrepayments(Double prepayments) {
		this.prepayments = prepayments;
	}

	public Long getSettledIndicator() {
		return settledIndicator;
	}

	public void setSettledIndicator(Long settledIndicator) {
		this.settledIndicator = settledIndicator;
	}

	public Double getTotalCharges() {
		return totalCharges;
	}

	public void setTotalCharges(Double totalCharges) {
		this.totalCharges = totalCharges;
	}

	public Double getTotalCosts() {
		return totalCosts;
	}

	public void setTotalCosts(Double totalCosts) {
		this.totalCosts = totalCosts;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

	public String getWardCode() {
		return wardCode;
	}

	public void setWardCode(String wardCode) {
		this.wardCode = wardCode;
	}
	
}