package com.hitzd.his.casehistory.beans;

import java.util.Date;

/**
 * VitalSignsRec generated by MyEclipse Persistence Tools
 */

public class VitalSignsRec implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 6302704848218997807L;

	private String patientId;

	private Long visitId;

	private Date recordingDate;

	private Date timePoint;

	private String vitalSigns;

	private Double vitalSignsValues;

	private String units;

	private String dbUser;

	private Long printFlag;

	private Date linkDate;

	public String getDbUser() {
		return dbUser;
	}

	public void setDbUser(String dbUser) {
		this.dbUser = dbUser;
	}

	public Date getLinkDate() {
		return linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public Long getPrintFlag() {
		return printFlag;
	}

	public void setPrintFlag(Long printFlag) {
		this.printFlag = printFlag;
	}

	public Date getRecordingDate() {
		return recordingDate;
	}

	public void setRecordingDate(Date recordingDate) {
		this.recordingDate = recordingDate;
	}

	public Date getTimePoint() {
		return timePoint;
	}

	public void setTimePoint(Date timePoint) {
		this.timePoint = timePoint;
	}

	public String getUnits() {
		return units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

	public Long getVisitId() {
		return visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

	public String getVitalSigns() {
		return vitalSigns;
	}

	public void setVitalSigns(String vitalSigns) {
		this.vitalSigns = vitalSigns;
	}

	public Double getVitalSignsValues() {
		return vitalSignsValues;
	}

	public void setVitalSignsValues(Double vitalSignsValues) {
		this.vitalSignsValues = vitalSignsValues;
	}

}